[package]
name = "techo"
version = "0.1.0-alpha.1"
edition = "2024"
description = "techō (手帳, てちょう) is a TUI application inspired by the experience of keeping a paper planner."
license = "MIT"
repository = "https://github.com/Noctsyndrome/techo"
homepage = "https://github.com/Noctsyndrome/techo"
readme = "README.md"
keywords = ["planner", "journal", "todo", "markdown"]
categories = ["command-line-utilities"]

[dependencies]
chrono = "0.4"
crossterm = "0.29"
ratatui = "0.30.2"
